---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worklode-ingress
  namespace: worklode
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - worklode.example.com
      secretName: worklode-tls
  rules:
    - host: worklode.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: worklode
                port:
                  number: 80
