---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: worklode
resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: worklode-migrations
    files:
      - migrations/0001_baseline.up.sql
      - migrations/0001_baseline.down.sql
