---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worklode-data
  namespace: worklode
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes-retain
  resources:
    requests:
      storage: 2Gi
