---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: work-tracker-data
  namespace: work-tracker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes-retain
  resources:
    requests:
      storage: 2Gi
