package store

import (
	"fmt"
	"testing"
	"time"
)

var wantTables = []string{
	"events",
	"actors",
	"tokens",
	"projects",
	"project_repos",
	"tasks",
	"task_edges",
	"leases",
	"issues",
	"pull_requests",
	"ci_runs",
	"reviews",
	"artifacts",
	"deployments",
	"runtime_events",
	"state_log",
	"github_user_tokens",
	"agent_sessions",
	"skills",
	"skill_versions",
	"index_chunks",
	"embedding_config",
	"docs",
	"doc_sections",
	"doc_edges",
	"doc_coverage_completed_with",
	"doc_revisions",
	"approvals",
}

func TestMigrateAppliesMigrations(t *testing.T) {
	t.Parallel()
	s := OpenTestStore(t)

	rows, err := s.db.Query(
		`SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'`)
	if err != nil {
		t.Fatalf("query information_schema.tables: %v", err)
	}
	defer rows.Close()

	got := map[string]bool{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			t.Fatalf("scan: %v", err)
		}
		got[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, table := range wantTables {
		if !got[table] {
			t.Errorf("table %q missing after migration", table)
		}
	}
}

func TestMigrateIdempotent(t *testing.T) {
	t.Parallel()
	s := OpenTestStore(t) // first Migrate happened here
	if err := s.Migrate(MigrationsDirForTests()); err != nil {
		t.Fatalf("second Migrate: %v", err)
	}
}

func TestMigrateRoundTrip(t *testing.T) {
	t.Parallel()
	s := OpenTestStore(t) // up happened here
	if err := s.MigrateDown(MigrationsDirForTests()); err != nil {
		t.Fatal(err)
	}
	if err := s.Migrate(MigrationsDirForTests()); err != nil {
		t.Fatal(err)
	}
}

// TestMigrateRoundTripWithLiveRally is TestMigrateRoundTrip with a rally
// that has done its job still in the database, one row in every table
// 0069's down migration must clear before DELETE FROM tasks: a blocks edge
// (task_edges), an active lease (leases — rally is not yet unclaimable, that
// lands in a later task), and, reachable through that same claimed session,
// a document it authored (docs.generated_by_task) and a note raised against
// it (doc_notes.task_id). All four are non-CASCADE foreign keys onto
// tasks(id), so any one of them left populated fails the whole MigrateDown.
// The doc and note rows are inserted directly (like insertDoc/
// seedDocNoteTask elsewhere in this package) since only the schema-level FK
// matters here, not CreateDoc/AddDocNote's own validation.
func TestMigrateRoundTripWithLiveRally(t *testing.T) {
	t.Parallel()
	s := openTaskStore(t) // up happened here, plus the horndb/stig fixtures

	rallyInput := defaultTaskInput()
	rallyInput.Kind = "rally"
	rally := createTask(t, s, taskTestNow, rallyInput)
	target := createTask(t, s, taskTestNow, defaultTaskInput())

	if err := addEdge(t, s, rally.ID, target.ID, "blocks"); err != nil {
		t.Fatalf("add blocks edge onto the rally: %v", err)
	}
	if _, err := s.Claim(t.Context(), rally.ID, "stig", "/tmp/wt", time.Hour); err != nil {
		t.Fatalf("claim the rally: %v", err)
	}

	var docID int64
	if err := s.db.QueryRowContext(t.Context(),
		`INSERT INTO docs (project_id, kind, number, slug, title, body, generated_by_task, created_at, updated_at)
		 VALUES ('horndb', 'spec', 1, 'rally-authored', 'title', 'body', $1, $2, $2)
		 RETURNING id`, rally.ID, taskTestNow).Scan(&docID); err != nil {
		t.Fatalf("insert doc generated by the rally: %v", err)
	}
	if _, err := s.db.ExecContext(t.Context(),
		`INSERT INTO doc_notes (doc_id, anchor, body, task_id, created_at)
		 VALUES ($1, 'sec-1', 'raised by the rally', $2, $3)`,
		docID, rally.ID, taskTestNow); err != nil {
		t.Fatalf("insert doc note raised by the rally: %v", err)
	}

	if err := s.MigrateDown(MigrationsDirForTests()); err != nil {
		t.Fatalf("migrate down with a live rally (edge + lease + doc + note): %v", err)
	}
	if err := s.Migrate(MigrationsDirForTests()); err != nil {
		t.Fatalf("migrate back up: %v", err)
	}
}

// TestMigrateReleasesDedicatedConnection guards against golang-migrate's pgx
// driver leaking the dedicated advisory-lock connection it opens via
// db.Conn(). A leaked connection makes Postgres refuse
// CREATE DATABASE ... TEMPLATE with SQLSTATE 55006 ("source database is
// being accessed by other users") even after Migrate has returned and the
// Store been closed — exactly the failure the template-database builder
// (testhelpers.go) used to work around by reaching into newMigrate/m.Close()
// directly instead of going through Store.Migrate().
func TestMigrateReleasesDedicatedConnection(t *testing.T) {
	t.Parallel()
	admin := adminConnForTest(t)
	dbName := randomDBName(t, "wl_test_leak_")
	if _, err := admin.Exec("CREATE DATABASE " + sqlIdent(dbName)); err != nil {
		t.Fatalf("create database %s: %v", dbName, err)
	}
	t.Cleanup(func() { dropDatabase(t, admin, dbName) })

	s := openTestDB(t, dbName)
	if err := s.Migrate(MigrationsDirForTests()); err != nil {
		t.Fatalf("migrate %s: %v", dbName, err)
	}
	if err := s.Close(); err != nil {
		t.Fatalf("close store for %s: %v", dbName, err)
	}

	cloneName := dbName + "_clone"
	stmt := fmt.Sprintf("CREATE DATABASE %s TEMPLATE %s", sqlIdent(cloneName), sqlIdent(dbName))
	if _, err := admin.Exec(stmt); err != nil {
		t.Fatalf("CREATE DATABASE ... TEMPLATE %s: %v (Migrate's dedicated connection was not released)", dbName, err)
	}
	t.Cleanup(func() { dropDatabase(t, admin, cloneName) })
}
