#!/usr/bin/env python3
"""Write docs/specs/inlined/: one self-contained reading copy per spec.

`scripts/currentspec.py` answers *which* section of which spec still states the
design. This script takes that same answer and renders the corpus it describes:
for every spec, a single markdown file in which

  * a section an effective `replaces` names is dropped -- its heading stays,
    marked, and the replacing text is inlined beneath it;
  * a section an effective `amends` names keeps its text and gains the
    amending text inlined beneath it;
  * a claim from a document that is not yet effective (a draft's proposal) is
    named as `pending` and never inlined, so nothing unsettled reads as design;
  * a document-scoped claim (`"."`, or a reference with no fragment) is a
    banner at the top rather than inlined text, because inlining a whole
    document under another document produces something nobody reads.

Inlining is transitive: an amendment that is itself amended is expanded, not
left as a reference. A view that stops partway shows a less-outdated version of
the design, which reads as current and is therefore worse than not rendering it.

This is spec 026 §3.2's `lode show --resolved` rendering, run over the whole
corpus and written to files, so a reader (or a document-ingesting tool that
takes URLs and not a shell) gets the consolidated view without the CLI.

**The output is a consolidated view, not a spec.** It is generated, never
hand-edited, and never a source: every file names the spec it came from and
every document it drew from. `docs/specs/` remains the corpus of record. The
gates that gate the corpus -- `secfmt.py`, `secmeta.py` -- skip this directory
for the same reason.

Usage: inlinespec.py [--check] [--with-drafts] [--out DIR]

  --check        report a missing or stale file instead of writing it (exit 1)
  --with-drafts  treat draft claims as effective -- what the corpus looks like
                 once the open drafts land
  --out DIR      write somewhere other than docs/specs/inlined
"""

import argparse
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True  # importing siblings must not litter scripts/
sys.path.insert(0, str(Path(__file__).resolve().parent))

import currentspec as cs  # noqa: E402
from secfmt import headings, split_front_matter  # noqa: E402
from secindex import ANCHOR, slug  # noqa: E402

REPO = cs.REPO
SPECS = cs.SPECS
OUT = "docs/specs/inlined"
HEADER = "<!-- Generated by scripts/inlinespec.py -- do not edit. -->"
MAX_DEPTH = 8  # a mutually-amending pair is a corpus defect, not a hang


def sections(path):
    """Return (preamble, [section]) for one document, in document order.

    A section is {key, level, heading, body}: `key` is the anchor secindex.py
    would give it, `heading` the heading line with its `{#anchor}` stripped,
    and `body` everything up to the next heading of any level. Keeping the body
    heading-exclusive is what lets a parent be dropped without taking its
    subsections with it -- supersession is per anchor (026 §2.3).
    """
    _, body = split_front_matter(path.read_text())
    lines = body.splitlines()
    marks, seen = [], {}
    for i, m in headings(body):
        num, anchor = m.group("num"), m.group("anchor")
        key = anchor or (f"sec-{num}" if num else slug(m.group("text")))
        seen[key] = seen.get(key, 0) + 1
        if seen[key] > 1:
            key = f"{key}-{seen[key]}"
        marks.append((i, key, len(m.group("hashes"))))

    preamble = "\n".join(lines[: marks[0][0]]) if marks else "\n".join(lines)
    out = []
    for n, (i, key, level) in enumerate(marks):
        end = marks[n + 1][0] if n + 1 < len(marks) else len(lines)
        out.append({
            "key": key,
            "level": level,
            "heading": ANCHOR.sub("", lines[i]).rstrip(),
            "body": "\n".join(lines[i + 1 : end]).strip("\n"),
        })
    return preamble.strip("\n"), out


def subtree(secs, key):
    """The text of one section and everything nested under it.

    "A section is always its whole subtree: inlining `#sec-2` carries
    `#sec-2.1` with it, because a claim against a parent is a claim against
    what it contains" (026 §3). Headings are flattened to bold lines so the
    borrowed text cannot reshape the outline of the document it lands in.
    """
    idx = {s["key"]: n for n, s in enumerate(secs)}
    if key not in idx:
        return None
    start = idx[key]
    parts = []
    for s in secs[start:]:
        if s is not secs[start] and s["level"] <= secs[start]["level"]:
            break
        text = re.sub(r"^#+[ \t]+", "", s["heading"]).strip()
        parts.append(f"**{text}**" + ("\n\n" + s["body"] if s["body"] else ""))
    return "\n\n".join(parts).strip("\n")


class Corpus:
    """The spec corpus, with the edges currentspec.py resolves it by."""

    def __init__(self, with_drafts=False):
        index = REPO / SPECS / "index.yaml"
        if not index.is_file():
            sys.exit(f"inlinespec: {index} missing -- run scripts/secindex.py")
        self.docs = cs.load(index)
        # The corpus is whatever the index names, so a spec added without
        # regenerating it would be absent from the views with nothing to show
        # for it. Fail loudly instead: a silently incomplete corpus is the one
        # defect these files exist to prevent.
        missing = sorted(
            p.relative_to(REPO).as_posix()
            for p in (REPO / SPECS).glob("*.md")
            if p.relative_to(REPO).as_posix() not in self.docs
        )
        if missing:
            sys.exit(
                "inlinespec: not in docs/specs/index.yaml: "
                + ", ".join(missing)
                + " -- run scripts/secindex.py"
            )
        self.replaced = cs.edges(self.docs, "replaces", "isReplacedBy")
        self.amended = cs.edges(self.docs, "amends", "amendedBy")
        self.with_drafts = with_drafts
        self._sections = {}

    def sections(self, path):
        if path not in self._sections:
            self._sections[path] = sections(REPO / path)
        return self._sections[path]

    def effective(self, src_path):
        """A claim only takes effect once the document making it is accepted."""
        st = cs.status_of(src_path, self.docs)
        return (
            st is None
            or st in cs.EFFECTIVE
            or (self.with_drafts and st == "draft")
        )

    def acting(self, edge, path, anchor):
        """(effective sources, pending sources) landing on exactly this target."""
        srcs = cs.sources_for(edge, path, anchor)
        return (
            [s for s in srcs if self.effective(s[0])],
            [s for s in srcs if not self.effective(s[0])],
        )

    def title(self, path):
        preamble, _ = self.sections(path)
        for line in preamble.splitlines():
            if line.startswith("# "):
                return line[2:].strip()
        return Path(path).stem


def consolidate(corpus, path, anchor, seen, drew_from, depth=0):
    """Blocks to inline under (path, anchor), transitively expanded.

    Each block leads with its attribution on its own line, so borrowed text is
    never mistakable for the document's own (026 §3.2).
    """
    if depth >= MAX_DEPTH or (path, anchor) in seen:
        return []
    seen = seen | {(path, anchor)}
    blocks = []
    for edge, verb in ((corpus.replaced, "superseding"), (corpus.amended, "amending")):
        for src_path, src_anchor in corpus.acting(edge, path, anchor)[0]:
            if not src_anchor:  # a doc-scoped claim is a banner, never inlined
                continue
            # A source outside this corpus -- a backbone-only spec, referenced
            # by shorthand -- has no text to fold in. notes() still names it,
            # so the section says it was amended and by what.
            if src_path not in corpus.docs:
                continue
            _, secs = corpus.sections(src_path)
            text = subtree(secs, src_anchor)
            if text is None:
                continue
            drew_from.add(src_path)
            ref = cs.name(src_path, src_anchor)
            nested = consolidate(corpus, src_path, src_anchor, seen, drew_from, depth + 1)
            blocks.append(
                f"**[{verb} {ref}]:**<br>\n\n"
                + "\n\n".join([text] + nested)
            )
    return blocks


def notes(corpus, path, anchor):
    """The one-line markers a section carries: what acts on it, and what only
    proposes to. Mirrors currentspec.py's annotations."""
    out = []
    for edge, word in ((corpus.replaced, "Replaced"), (corpus.amended, "Amended")):
        eff, pending = corpus.acting(edge, path, anchor)
        out += [f"{word} by `{cs.name(*s)}`" for s in eff]
        out += [f"Pending `{cs.name(*s)}` (not yet effective)" for s in pending]
    return out


def render(corpus, path):
    """The consolidated markdown for one spec."""
    doc = corpus.docs[path]
    preamble, secs = corpus.sections(path)
    drew_from = set()

    body, dropped = [], []
    for s in secs:
        anchor = s["key"]
        replaced_by = corpus.acting(corpus.replaced, path, anchor)[0]
        line_notes = notes(corpus, path, anchor)
        blocks = consolidate(corpus, path, anchor, set(), drew_from)

        body.append(s["heading"])
        if line_notes:
            body.append("> " + "  \n> ".join(line_notes))
        if replaced_by:
            dropped.append((anchor, [cs.name(*x) for x in replaced_by]))
            body.append(
                "> The text of this section no longer states the design and is "
                f"omitted here; it is still in the source spec at `{path}`."
            )
        elif s["body"]:
            body.append(s["body"])
        body += blocks

    doc_notes = []
    for edge, word in ((corpus.replaced, "Superseded"), (corpus.amended, "Amended")):
        eff, pending = corpus.acting(edge, path, None)
        doc_notes += [f"{word} as a whole by `{cs.name(*s)}`" for s in eff]
        doc_notes += [f"Pending `{cs.name(*s)}` (not yet effective)" for s in pending]

    banner = [
        HEADER,
        "",
        f"# {corpus.title(path)} — consolidated view",
        "",
        "> **This is a generated consolidated view, not a spec.** It is one spec's",
        f"> text with every amendment and supersession that is in force folded in.",
        f"> Source of record: [`{path}`](../{Path(path).name}) — status **{doc['status']}**.",
    ]
    if doc_notes:
        banner.append(">")
        banner += ["> " + n + "." for n in doc_notes]
    if drew_from:
        banner.append(">")
        banner.append(
            "> Text was drawn from: "
            + ", ".join(f"`{Path(p).name}`" for p in sorted(drew_from))
            + "."
        )
    banner += [
        ">",
        "> Inlined blocks are marked `**[amending …]**` or `**[superseding …]**`",
        "> and name the section they came from. Claims from documents that are not",
        "> yet accepted are listed as `pending` and are not folded in.",
        "",
        "---",
        "",
    ]

    tail = []
    if dropped:
        tail = ["", "---", "", "## Sections omitted from this view", ""]
        tail += [
            f"- `{a}` — replaced by {', '.join(f'`{b}`' for b in by)}"
            for a, by in dropped
        ]

    parts = ["\n".join(banner)]
    if preamble:
        # The source H1 is already in the banner; keep the rest of the preamble.
        rest = "\n".join(
            l for l in preamble.splitlines() if not l.startswith("# ")
        ).strip("\n")
        if rest:
            parts.append(rest)
    parts.append("\n\n".join(p for p in body if p.strip()))
    if tail:
        parts.append("\n".join(tail).strip("\n"))
    return "\n\n".join(p for p in parts if p.strip()).rstrip() + "\n"


def render_superseded(corpus, path, by):
    """A superseded document keeps a file, so the set of URLs stays complete,
    but not its text: it no longer states the design anywhere."""
    successors = ", ".join(f"`{b}`" for b in by) or "no successor recorded"
    return "\n".join([
        HEADER,
        "",
        f"# {corpus.title(path)} — superseded",
        "",
        f"> **This spec is superseded and its text is not reproduced here.**",
        f"> Source of record: [`{path}`](../{Path(path).name}) — status "
        f"**{corpus.docs[path]['status']}**.",
        f"> Superseded by: {successors}.",
        "",
    ]) + "\n"


def render_readme(corpus, files, superseded, dropped):
    lines = [
        HEADER,
        "",
        "# Consolidated spec views",
        "",
        "One file per spec in `docs/specs/`, with every amendment and",
        "supersession that is in force folded into the text (spec 026 §3.2).",
        "Generated by `scripts/inlinespec.py`; **not** the corpus of record —",
        "`docs/specs/` is. Nothing here should be edited by hand, cited as a",
        "source, or amended: fix the spec and regenerate.",
        "",
        "The purpose is a reading path. A spec's design is often spread across",
        "the specs that later amended it, and following that by hand means",
        "opening five documents and tracking which of their claims are in force.",
        "These files do that resolution once.",
        "",
        "## Documents",
        "",
    ]
    for path in files:
        lines.append(
            f"- [`{Path(path).name}`]({Path(path).name}) — "
            f"{corpus.title(path)} ({corpus.docs[path]['status']})"
        )
    if superseded:
        lines += ["", "## Superseded documents", ""]
        for path, by in superseded:
            lines.append(
                f"- [`{Path(path).name}`]({Path(path).name}) — superseded by "
                + (", ".join(f"`{b}`" for b in by) or "no successor recorded")
            )
    if dropped:
        lines += ["", "## Replaced sections", "",
                  "Omitted from the views above; the text is still in the source spec.", ""]
        for sec, by in dropped:
            lines.append(f"- `{sec}` → {', '.join(f'`{b}`' for b in by)}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--with-drafts", action="store_true")
    ap.add_argument("--out", default=OUT)
    a = ap.parse_args()

    corpus = Corpus(a.with_drafts)
    out_dir = (REPO / a.out).resolve()

    written, superseded, dropped, files = {}, [], [], []
    for path in sorted(corpus.docs):
        whole = [s for s in cs.sources_for(corpus.replaced, path, None)
                 if corpus.effective(s[0])]
        if corpus.docs[path]["status"] == "superseded" or whole:
            by = [cs.name(*s) for s in whole]
            superseded.append((path, by))
            written[Path(path).name] = render_superseded(corpus, path, by)
            continue
        files.append(path)
        written[Path(path).name] = render(corpus, path)
        for s in corpus.sections(path)[1]:
            reps = corpus.acting(corpus.replaced, path, s["key"])[0]
            if reps:
                dropped.append((cs.name(path, s["key"]), [cs.name(*x) for x in reps]))

    written["README.md"] = render_readme(corpus, files, superseded, dropped)

    stale = False
    for name, text in sorted(written.items()):
        target = out_dir / name
        have = target.read_text() if target.is_file() else None
        if have == text:
            continue
        stale = True
        rel = target.relative_to(REPO).as_posix()
        if a.check:
            print(f"inlinespec: {rel} is {'stale' if have else 'missing'}", file=sys.stderr)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text)
            print(f"inlinespec: wrote {rel}", file=sys.stderr)

    if out_dir.is_dir():
        for extra in sorted(out_dir.glob("*.md")):
            if extra.name in written:
                continue
            stale = True
            rel = extra.relative_to(REPO).as_posix()
            if a.check:
                print(f"inlinespec: {rel} is not generated by this script", file=sys.stderr)
            else:
                extra.unlink()
                print(f"inlinespec: removed {rel}", file=sys.stderr)

    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
