#!/usr/bin/env python3
"""Hermetic tests for scripts/secindex.py's --check exit status.

WL-92: --check must fail (non-zero) when an index is stale, or nothing that
wires it into a gate (CI, pre-commit) can ever fail on a stale index.
"""

import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

DOC = """\
# Doc

## 1. First section {#sec-1}

## 2. Second section {#sec-2}
"""


def run_secindex(files, args, index_yaml=None):
    """Run the real script in an isolated repo, optionally pre-seeding
    docs/specs/index.yaml so the fixture can be made stale or current."""
    with tempfile.TemporaryDirectory() as tmp:
        repo = Path(tmp)
        scripts = repo / "scripts"
        scripts.mkdir()
        for name in ("secindex.py", "secfmt.py"):
            shutil.copy2(ROOT / "scripts" / name, scripts / name)
        for rel, content in files.items():
            path = repo / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        if index_yaml is not None:
            (repo / "docs/specs").mkdir(parents=True, exist_ok=True)
            (repo / "docs/specs/index.yaml").write_text(index_yaml)
        return subprocess.run(
            [sys.executable, "scripts/secindex.py", *args, "docs/specs"],
            cwd=repo, capture_output=True, text=True, check=False,
        )


class CheckExitStatusTest(unittest.TestCase):
    def test_check_exits_zero_when_current(self):
        # Generate the current index for this fixture, then assert --check
        # against it reports clean.
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            scripts = repo / "scripts"
            scripts.mkdir()
            for name in ("secindex.py", "secfmt.py"):
                shutil.copy2(ROOT / "scripts" / name, scripts / name)
            (repo / "docs/specs").mkdir(parents=True)
            (repo / "docs/specs/s.md").write_text(DOC)
            # First run writes the missing index; write mode also exits 1 on
            # a write (covered by test_write_mode_..._below), so don't assert
            # on this priming call's exit status.
            subprocess.run(
                [sys.executable, "scripts/secindex.py", "docs/specs"],
                cwd=repo, capture_output=True, text=True, check=False,
            )
            result = subprocess.run(
                [sys.executable, "scripts/secindex.py", "--check", "docs/specs"],
                cwd=repo, capture_output=True, text=True, check=False,
            )
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            self.assertEqual(result.stderr, "")

    def test_check_exits_nonzero_when_stale(self):
        result = run_secindex(
            {"docs/specs/s.md": DOC}, ["--check"],
            index_yaml="# Generated by scripts/secindex.py -- do not edit.\n",
        )
        self.assertNotEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("docs/specs/index.yaml is stale", result.stderr)

    def test_check_exits_nonzero_when_missing(self):
        result = run_secindex({"docs/specs/s.md": DOC}, ["--check"])
        self.assertNotEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("docs/specs/index.yaml is missing", result.stderr)

    def test_write_mode_also_exits_nonzero_when_it_had_to_rewrite(self):
        result = run_secindex(
            {"docs/specs/s.md": DOC}, [],
            index_yaml="# Generated by scripts/secindex.py -- do not edit.\n",
        )
        self.assertNotEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("wrote docs/specs/index.yaml", result.stderr)


if __name__ == "__main__":
    unittest.main()
