#!/usr/bin/env python3
"""Write docs/specs/index.yaml and docs/plans/index.yaml: every document's
sections, keyed by anchor.

The index is a lookup table for agents and humans: which section of which
document covers a subject, without opening (or grepping) 25 specs. It is
generated, never hand-edited.

Usage: secindex.py [--check] [dir...]

  --check   report a missing or stale index instead of writing it

Exit 1 when an index was stale, whether it was rewritten or only reported, so
the pre-commit hook fails and the author re-stages the regenerated file.

Directories default to docs/specs and docs/plans. Each key is the document's
repo-relative path; each section key is its `{#sec-N}` anchor when it has one,
else `sec-<number>` for a numbered heading, else a slug of the heading text
(plans number their sections in prose — "## Task 3: ..." — so they land here).
Values are the heading line as written, minus the anchor.
"""

import argparse
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True  # importing secfmt must not litter scripts/
sys.path.insert(0, str(Path(__file__).resolve().parent))
from secfmt import headings, split_front_matter  # noqa: E402

DEFAULT_ROOTS = ("docs/specs", "docs/plans")
INDEX_NAME = "index.yaml"
HEADER = "# Generated by scripts/secindex.py -- do not edit.\n"


def slug(text):
    """Kebab-case key for a heading that carries neither anchor nor number."""
    s = re.sub(r"[^\w\s-]", "", text.lower())
    return re.sub(r"[\s_-]+", "-", s).strip("-") or "section"


def quote(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


ANCHOR = re.compile(r"[ \t]*\{#[\w.\-]+\}[ \t]*$")


def sections_of(path):
    """Return [(key, heading line)] for one document, in document order."""
    _, body = split_front_matter(path.read_text())
    lines = body.splitlines()
    out, seen = [], {}
    for i, m in headings(body):
        num, anchor = m.group("num"), m.group("anchor")
        key = anchor or (f"sec-{num}" if num else slug(m.group("text")))
        seen[key] = seen.get(key, 0) + 1
        if seen[key] > 1:
            key = f"{key}-{seen[key]}"
        out.append((key, ANCHOR.sub("", lines[i]).rstrip()))
    return out


def render(root, repo):
    """Return the index.yaml text for one directory of documents."""
    parts = [HEADER]
    for path in sorted(root.glob("*.md")):
        parts.append(f"{path.relative_to(repo).as_posix()}:\n  sections:\n")
        rows = sections_of(path)
        if not rows:
            parts[-1] = parts[-1][: -len("\n")] + " {}\n"
            continue
        for key, line in rows:
            parts.append(f"    {key}: {quote(line)}\n")
    return "".join(parts)


def main():
    a = argparse.ArgumentParser()
    a.add_argument("--check", action="store_true")
    a.add_argument("dirs", nargs="*", default=None)
    a = a.parse_args()

    repo = Path(__file__).resolve().parent.parent
    roots = [Path(d) for d in a.dirs] if a.dirs else [repo / d for d in DEFAULT_ROOTS]

    stale = False
    for root in roots:
        root = root.resolve()
        if not root.is_dir():
            print(f"secindex: {root} is not a directory", file=sys.stderr)
            return 2
        want = render(root, repo)
        index = root / INDEX_NAME
        have = index.read_text() if index.exists() else None
        if have == want:
            continue
        rel = index.relative_to(repo).as_posix()
        stale = True
        if a.check:
            print(f"secindex: {rel} is {'stale' if have else 'missing'}", file=sys.stderr)
        else:
            index.write_text(want)
            print(f"secindex: wrote {rel}", file=sys.stderr)
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
