package mdrender_test

import (
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/sunstoneinstitute/worklode/internal/mdrender"
)

// The editor's shortcode completion offers names from
// internal/ui/assets/emoji.json (generated by scripts/gen-emoji.py); this
// package is what substitutes them when the body renders. A name the popup
// offers that renders as literal ":name:" is a broken suggestion, so every
// entry is checked against the real render path.
func TestEmojiAssetMatchesRenderer(t *testing.T) {
	raw, err := os.ReadFile("../ui/assets/emoji.json")
	if err != nil {
		t.Fatalf("read emoji asset: %v", err)
	}
	var emoji map[string]string
	if err := json.Unmarshal(raw, &emoji); err != nil {
		t.Fatalf("parse emoji asset: %v", err)
	}
	if len(emoji) < 1000 {
		t.Fatalf("emoji asset has %d shortcodes, expected the full GitHub set", len(emoji))
	}
	if got := emoji["smile"]; got != "😄" {
		t.Errorf("emoji[smile] = %q, want %q", got, "😄")
	}

	for name, glyph := range emoji {
		got := string(mdrender.Body(mdrender.ProjectKeys{}, ":"+name+":"))
		if !strings.Contains(got, glyph) {
			t.Errorf(":%s: rendered as %q, want the glyph %q", name, got, glyph)
		}
	}
}
