---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: work-tracker
resources:
  - ../../base
  - externalsecret-work-tracker-secrets.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: work-tracker
        labels:
          sunstone.institute/ghcr-pull: "true"
  - target:
      kind: ConfigMap
      name: work-tracker-config
    patch: |-
      - op: replace
        path: /data/WT_CLUSTER_ENV_MAP
        value: "dev=dev,hzdev=dev,prod=prod,hzprod=prod,admin=prod"
  - target:
      kind: Ingress
      name: work-tracker-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - work-tracker.hzdev.sunstoneinstitute.ai
      - op: replace
        path: /spec/rules/0/host
        value: work-tracker.hzdev.sunstoneinstitute.ai
images:
  - name: ghcr.io/sunstoneinstitute/work-tracker
    newTag: latest
