#!/usr/bin/env bash
# capture-rules.sh — promote the agent home's autoMode block into a PR.
#
# Run from the repository root by .github/workflows/agent-host-rules.yml.
# Reads the live rules off the box, writes them to the committed copy the
# babysitter installs on every tick, and opens a pull request if they differ.
set -euo pipefail

AGENT_ROOT=${AGENT_ROOT:-/home/ghrunner/gha-agent}
RULES_FILE=${RULES_FILE:-.github/agent-host/settings.json}
LIVE="$AGENT_ROOT/home/.claude/settings.json"

if [ ! -r "$LIVE" ]; then
  echo "::error::$LIVE not found — run this workflow with action=setup first"
  exit 1
fi

# Only the autoMode block travels. The live file also carries whatever else
# that session accumulated, and none of it belongs in the repository.
if ! python3 -c '
import json, sys
live = json.load(open(sys.argv[1]))
auto = live.get("autoMode")
if not auto:
    sys.exit("no autoMode block in " + sys.argv[1])
json.dump({"autoMode": auto}, open(sys.argv[2], "w"), indent=2, sort_keys=True)
open(sys.argv[2], "a").write("\n")
' "$LIVE" "$RULES_FILE"; then
  echo "::error::could not read an autoMode block out of $LIVE"
  exit 1
fi

if git diff --quiet -- "$RULES_FILE"; then
  echo "auto-mode rules are unchanged; nothing to promote"
  {
    echo "### Auto-mode rules"
    echo ""
    echo "No change: the committed rules already match what is on hel01."
  } >> "${GITHUB_STEP_SUMMARY:-/dev/null}"
  exit 0
fi

branch="agent-host/auto-mode-rules-${GITHUB_RUN_ID:-manual}"
git config user.name "worklode agent host"
git config user.email "noreply@sunstoneinstitute.ai"
git checkout -b "$branch"
git add -- "$RULES_FILE"
git commit -q -m "agent host: refresh auto-mode rules

Captured from /auto-mode-setup on hel01. These are the rules the unattended
worker sessions run under; review the diff as a permission change, not as
configuration."
git push -u origin "$branch"

gh pr create \
  --title "agent host: refresh auto-mode rules" \
  --body "$(printf '%s\n' \
    'Captured from `/auto-mode-setup` on hel01 by the Agent host rules workflow.' \
    '' \
    'This is the ruleset the unattended worker sessions run under. Review it as' \
    'a permission change: the runner user is in the docker group, which' \
    '`docs/self-hosted-runner.md` calls root-equivalent on that host.' \
    '' \
    'The babysitter installs this file to the agent HOME on every tick. It has' \
    'to be user scope — the auto-mode classifier ignores a repository'"'"'s own' \
    '`.claude/settings.json` by design.' \
    '' \
    '---' \
    '_Generated by [Claude Code](https://claude.ai/code)_')"

{
  echo "### Auto-mode rules"
  echo ""
  echo "Opened a pull request from \`$branch\`."
} >> "${GITHUB_STEP_SUMMARY:-/dev/null}"
